"""Heal corrupted text with DirichletFM — approach C (localize-then-inpaint).

End-to-end "self-healing" inference on a FROZEN DirichletFM checkpoint, for the
realistic setting where **we do not know which tokens are corrupted**. One
backbone serves two roles (no new network is trained beyond a single linear
head):

  1. LOCALIZE — a per-token linear *energy* head on frozen DirichletFM features
     (the BayesLinHead recipe, ``scripts/ood_bayes_linear.py``): valid char -> E~0,
     corrupt char -> E>=margin. Features are the DETERMINISTIC Dirichlet-mean
     backbone activations at ``t_eval`` (``_perpos_feats``). Per-token energy is
     thresholded into a binary heal-mask; the threshold is calibrated to a target
     false-positive rate on clean tokens, and the headline operating point is
     selected by F1 on the held-out CALIBRATION set (never on the demo).

  2. INPAINT — a masked-Euler integration of the DirichletFM marginal vector
     field (``t: 1 -> t_max``). Trusted (un-flagged) positions are re-imposed
     every step via the deterministic Dirichlet mean concentrated on the observed
     token (RePaint-style known-region conditioning, adapted to the Dirichlet
     path); flagged positions are generated by the field, conditioned on the
     trusted context through the non-causal backbone. Trusted tokens are restored
     verbatim at the end.

The ground-truth corruption mask is used ONLY to *score* the demo result — never
to drive healing or to select the operating point. The demo corruption is
averaged over ``--n-seeds`` independent realizations to give an honest CI.

Headline metrics (per-region, correctly denominated):
  fix_rate     = P(corrupt token -> correct)           [recovery, want high]
  damage_rate  = P(clean token   -> broken)            [collateral, want low]
  net/corrupt  = (fixed - damaged) / n_corrupt          [net tokens recovered per corrupt]
The whole-sequence delta is reported only as a (dilution-dominated) diagnostic:
it equals (fixed - damaged)/(B*L) and is structurally capped near corrupt_rate
because ~(1-corrupt_rate) of positions are restored verbatim.

Honest ceiling: this is character-level text8. Healing moves toward
n-gram-plausible character strings, not toward correct words/meaning. It is a
*mechanism demonstration* of transport-based, OOD-localized healing.

Usage:
    python scripts/heal_dirichlet.py \
        --ckpt runs/sflm_bench_a100_20g_L256_d1280L14_full/DirichletFM/epoch_final.pt \
        --corrupt-rate 0.15 --n-demo 16 --n-seeds 5 --out heal_out/heal.json
"""

from __future__ import annotations

import argparse
import json
import math
import statistics
import sys
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F


def _bootstrap() -> None:
    repo_root = Path(__file__).resolve().parent.parent
    src = repo_root / "src"
    if str(src) not in sys.path:
        sys.path.insert(0, str(src))
    if str(repo_root) not in sys.path:
        sys.path.append(str(repo_root))


_bootstrap()

from scripts.ood_variance_perpos import _load_dirichletfm, _perpos_feats  # noqa: E402
from aitchinson_flow.training import build_training_datamodule  # noqa: E402
from aitchinson_flow.data.corruption import corrupt_token_ids  # noqa: E402
from aitchinson_flow.models.dirichlet_fm import (  # noqa: E402
    _conditional_velocity_factor,
)

_ALPH = "abcdefghijklmnopqrstuvwxyz "  # text8 K=27 decode (a-z + space)


def _decode(ids) -> str:
    return "".join(_ALPH[int(i)] if int(i) < len(_ALPH) else "?" for i in ids)


# --------------------------------------------------------------------------- #
# Localizer: per-token linear energy head on frozen DirichletFM features.
# --------------------------------------------------------------------------- #
def train_localizer(model, fit_tok, t_eval, device, *, train_rate, margin, steps, lr, seed):
    """Train the per-token energy head + standardiser on clean/corrupt features.

    Returns a ``score(token_ids) -> E_t (B,L)`` closure. Mirrors the energy-head
    half of ``scripts/ood_bayes_linear.py`` (raw d_model features, no PCA, no
    Laplace variance)."""
    K = model.K
    fc = _perpos_feats(model, fit_tok, t_eval, device)  # (Nf, L, d) clean
    d = fc.shape[-1]
    corr_tok = corrupt_token_ids(
        fit_tok.clone(), vocab_size=K, corrupt_rate=train_rate, seed=seed
    )
    fk = _perpos_feats(model, corr_tok, t_eval, device)  # (Nf, L, d) corrupted
    label_corr = (corr_tok != fit_tok).reshape(-1)  # (Nf*L,) bool

    mu = fc.reshape(-1, d).mean(0)
    sigma = fc.reshape(-1, d).std(0).clamp_min(1e-6)

    def _proj(h_flat):
        m, s = mu.to(h_flat.device), sigma.to(h_flat.device)
        return (h_flat - m) / s

    zc = _proj(fc.reshape(-1, d)).to(device)
    zk = _proj(fk.reshape(-1, d)).to(device)
    yk = label_corr.to(device)

    head = nn.Linear(d, 1).to(device)
    opt = torch.optim.Adam(head.parameters(), lr=lr)
    zpos = torch.cat([zc, zk[~yk]], 0)  # valid chars (clean + unchanged-corrupt)
    zneg = zk[yk]                       # corrupted chars
    for step in range(steps):
        opt.zero_grad()
        ep = head(zpos).squeeze(-1)
        en = head(zneg).squeeze(-1)
        loss = ep.pow(2).mean() + torch.relu(margin - en).mean()
        loss.backward()
        opt.step()
        if step % 200 == 0 or step == steps - 1:
            print(f"  [head] step {step:4d}  E_valid={ep.mean():+.3f}  "
                  f"E_corrupt={en.mean():+.3f}  gap={(en.mean() - ep.mean()):+.3f}")
    head.eval()

    @torch.no_grad()
    def score(tok):
        h = _perpos_feats(model, tok, t_eval, device)  # (B, L, d)
        b, Lq, _ = h.shape
        z = _proj(h.reshape(-1, d)).to(device)
        return head(z).squeeze(-1).reshape(b, Lq).cpu()  # (B, L)

    return score, d


# --------------------------------------------------------------------------- #
# Localizer (NLL): training-free denoiser surprise — no head, no fit set.
#
# The localizer is the model's OWN per-token negative log-likelihood read at a
# low path-time t_nll (~3): NLL_t = -log softmax(f(x_t, t))[observed_token]. The
# deterministic Dirichlet-mean input barely reveals the token, so the non-causal
# denoiser must predict each position from CONTEXT; a corrupted / out-of-place
# token then gets low predicted probability => high NLL => flagged. Same
# (score, d) interface as train_localizer, so it drops into the identical
# calibrate -> inpaint -> score pipeline for an honest A/B vs the BLR head.
# Standalone detector: scripts/ood_denoiser_nll.py.
# --------------------------------------------------------------------------- #
def make_nll_localizer(model, t_nll, device, *, chunk=16):
    """Return a ``score(token_ids) -> NLL_t (B,L)`` closure (higher == more
    likely corrupt). Reuses model.forward (the generation softmax); no training."""
    K = model.K

    @torch.no_grad()
    def score(tok):
        outs = []
        for i in range(0, tok.shape[0], chunk):
            tb = tok[i:i + chunk].to(device).long()
            b, Lq = tb.shape
            beta = torch.ones(b, Lq, K, device=device)
            beta.scatter_(-1, tb.unsqueeze(-1), float(t_nll))
            x_t = beta / beta.sum(-1, keepdim=True)          # deterministic Dir mean
            tt = torch.full((b,), float(t_nll), device=device)
            logits = model.forward(x_t, tt)                  # (b,L,K) denoiser logits
            nll = -F.log_softmax(logits, -1).gather(
                -1, tb.unsqueeze(-1)).squeeze(-1)            # (b,L)
            outs.append(nll.cpu())
        return torch.cat(outs)

    return score, 0  # d unused (no feature head); kept for signature parity


def _auroc(pos: torch.Tensor, neg: torch.Tensor) -> float:
    """AUROC with ``pos`` the class that should score higher (corrupt tokens)."""
    pos, neg = pos.flatten().float(), neg.flatten().float()
    if pos.numel() == 0 or neg.numel() == 0:
        return float("nan")
    comb = torch.cat([pos, neg])
    order = comb.argsort()
    ranks = torch.empty_like(order, dtype=torch.float)
    ranks[order] = torch.arange(1, comb.numel() + 1, dtype=torch.float)
    return float(
        (ranks[: pos.numel()].sum() - pos.numel() * (pos.numel() + 1) / 2)
        / (pos.numel() * neg.numel())
    )


# --------------------------------------------------------------------------- #
# Localizer (GP): per-token sparse-variational GP on frozen DirichletFM
# features.
#
# mode="oneclass" (default, recommended): the GP is fit ONLY on valid (clean)
#   tokens — corruption is never seen in training. It is an SVGP *regression to
#   y=0* (ELBO: data-NLL + KL), so the data-fit term drives predictive variance
#   DOWN on the clean manifold and it reverts to the high prior off-manifold.
#   Inducing points are seeded on clean features and the lengthscale is small &
#   fixed, giving sharp clean-vs-corrupt variance contrast. OOD score = the
#   predictive VARIANCE (Matern-kernel analog of BLR's one-class Mahalanobis).
#   This is the "the generator's own uncertainty catches OOD" detector.
#
# mode="contrastive": the earlier discriminative variant — energy hinge on
#   clean/corrupt negatives; OOD score = GP posterior MEAN (energy). Kept for
#   comparison. (Its variance channel collapses — see docs.)
#
# Either way this drops into the exact same calibrate->inpaint->score pipeline
# as the linear head for an honest A/B (same (score, d) signature).
# --------------------------------------------------------------------------- #
def train_gp_localizer(model, fit_tok, t_eval, device, *, mode, train_rate, margin,
                       steps, lr, seed, d_latent, num_inducing, margin_var,
                       lambda_var, lambda_kl, batch, var_weights,
                       lengthscale_scale, learn_lengthscale, noise_init):
    """Fit an SVGP localizer on frozen per-token features; return (score, d)."""
    from aitchinson_flow.models.sparse_gp import _SparseGP

    K = model.K
    # Disjoint within-fit split: train on fit_a, pick the combine-weight on fit_b.
    n = fit_tok.shape[0]
    n_sel = max(1, n // 5)
    fit_a, fit_b = fit_tok[:n - n_sel], fit_tok[n - n_sel:]

    fc = _perpos_feats(model, fit_a, t_eval, device)            # (Na, L, d) clean
    d = fc.shape[-1]
    mu = fc.reshape(-1, d).mean(0)
    sigma = fc.reshape(-1, d).std(0).clamp_min(1e-6)

    def _std(h_flat):
        m, s = mu.to(h_flat.device), sigma.to(h_flat.device)
        return (h_flat - m) / s

    zc = _std(fc.reshape(-1, d)).to(device)                     # clean tokens

    # Projection: d_latent<=0 => identity (raw standardized features, the
    # BLR-comparable choice — isolates the kernel's contribution over BLR).
    use_proj = bool(d_latent and d_latent > 0)
    dl = int(d_latent) if use_proj else d
    proj = nn.Linear(d, dl).to(device) if use_proj else nn.Identity()

    def _phi(z):
        return proj(z) if use_proj else z

    gp = _SparseGP(dl, num_inducing).to(device)
    # Small, FIXED lengthscale (sharp variance contrast off-manifold); seed
    # inducing points ON the clean manifold so "far from Z" == off-distribution.
    with torch.no_grad():
        gp.log_lengthscale.copy_(torch.tensor(math.log(math.sqrt(dl) * lengthscale_scale)))
        idx = torch.randperm(zc.shape[0])[:num_inducing]
        gp.Z.copy_(_phi(zc[idx]))
    gp.log_lengthscale.requires_grad_(bool(learn_lengthscale))

    params = [p for p in gp.parameters() if p.requires_grad]
    if use_proj:
        params += list(proj.parameters())
    g = torch.Generator().manual_seed(seed)

    if mode == "oneclass":
        log_noise = nn.Parameter(torch.tensor(math.log(noise_init), device=device))
        opt = torch.optim.Adam(params + [log_noise], lr=lr)
        ntot = zc.shape[0]
        for step in range(steps):
            opt.zero_grad()
            ib = torch.randint(0, ntot, (batch,), generator=g).to(device)
            o = gp(_phi(zc[ib]))
            sig2 = log_noise.exp()
            # negative SVGP ELBO for regression to y=0: per-point E_q[-log p(y|f)]
            nll = 0.5 * (math.log(2 * math.pi) + log_noise
                         + (o.mean.pow(2) + o.variance) / sig2)
            kl = gp.kl_divergence()
            loss = nll.mean() + lambda_kl * kl / ntot
            loss.backward()
            opt.step()
            if step % 300 == 0 or step == steps - 1:
                print(f"  [gp/oneclass] step {step:4d}  |mean|_clean={o.mean.abs().mean():.3f}"
                      f"  V_clean={o.variance.mean():.3f}  sig2={sig2.item():.3f}"
                      f"  ls={gp.log_lengthscale.exp().item():.2f}  kl={kl.item():.2f}")
        primary = "variance"
    else:  # contrastive
        corr_a = corrupt_token_ids(fit_a.clone(), vocab_size=K,
                                   corrupt_rate=train_rate, seed=seed)
        fk = _perpos_feats(model, corr_a, t_eval, device)
        yk = (corr_a != fit_a).reshape(-1).to(device)
        zk = _std(fk.reshape(-1, d)).to(device)
        zpos = torch.cat([zc, zk[~yk]], 0)
        zneg = zk[yk]
        npos, nneg = zpos.shape[0], zneg.shape[0]
        opt = torch.optim.Adam(params, lr=lr)
        for step in range(steps):
            opt.zero_grad()
            ip = torch.randint(0, npos, (batch,), generator=g).to(device)
            ineg = torch.randint(0, nneg, (batch,), generator=g).to(device)
            dp = gp(_phi(zpos[ip]))
            dn = gp(_phi(zneg[ineg]))
            mean_loss = dp.mean.pow(2).mean() + torch.relu(margin - dn.mean).mean()
            var_loss = dp.variance.mean() + torch.relu(margin_var - dn.variance).mean()
            kl = gp.kl_divergence()
            loss = mean_loss + lambda_var * var_loss + lambda_kl * kl / batch
            loss.backward()
            opt.step()
            if step % 300 == 0 or step == steps - 1:
                print(f"  [gp/contrastive] step {step:4d}  E_valid={dp.mean.mean():+.3f}  "
                      f"E_corrupt={dn.mean.mean():+.3f}  V_valid={dp.variance.mean():.3f}  "
                      f"V_corrupt={dn.variance.mean():.3f}  kl={kl.item():.2f}")
        primary = "energy"

    gp.eval()
    if use_proj:
        proj.eval()

    @torch.no_grad()
    def _energy_var(tok):
        h = _perpos_feats(model, tok, t_eval, device)          # (B, L, d)
        b, Lq, _ = h.shape
        z = _std(h.reshape(-1, d)).to(device)
        Es, Vs = [], []
        for i in range(0, z.shape[0], 16384):
            o = gp(_phi(z[i:i + 16384]))
            Es.append(o.mean.cpu())
            Vs.append(o.variance.cpu())
        E = torch.cat(Es).reshape(b, Lq)
        V = torch.cat(Vs).reshape(b, Lq)
        return E, V

    # The OOD score combines the primary channel with the other one; the
    # combine-weight is selected GT-free on a held-out fit slice (never the
    # demo). One-class: variance + w*mean^2. Contrastive: energy + w*variance.
    def _combine(E, V, w):
        return (V + w * E.pow(2)) if primary == "variance" else (E + w * V)

    sel_corr = corrupt_token_ids(fit_b.clone(), vocab_size=K,
                                 corrupt_rate=train_rate, seed=seed + 7)
    Eb, Vb = _energy_var(sel_corr)
    yb = (sel_corr != fit_b)
    au_var = _auroc(Vb[yb], Vb[~yb])
    au_eng = _auroc(Eb[yb], Eb[~yb])
    print(f"  [gp] held-out per-token AUROC: variance={au_var:.4f}  energy={au_eng:.4f}  "
          f"(primary={primary})")
    best_w, best_au = float(var_weights[0]), -1.0
    for w in var_weights:
        w = float(w)
        au = _auroc(_combine(Eb, Vb, w)[yb], _combine(Eb, Vb, w)[~yb])
        print(f"        w={w:>5.2f}  combined AUROC={au:.4f}")
        if au > best_au:
            best_au, best_w = au, w
    print(f"  [gp] selected combine-weight w={best_w} (held-out AUROC={best_au:.4f})")

    @torch.no_grad()
    def score(tok):
        E, V = _energy_var(tok)
        return _combine(E, V, best_w)

    return score, d


def calibrate_threshold(score, clean_tok, corrupt_tok, *, target_fpr):
    """Threshold giving ~target_fpr on clean tokens; report its precision/recall/F1
    on the held-out calibration corrupt batch (used for GT-free operating-point
    selection)."""
    E_clean = score(clean_tok).reshape(-1)
    thr = float(torch.quantile(E_clean, 1.0 - target_fpr))
    E_corr = score(corrupt_tok)
    true_corrupt = (corrupt_tok != clean_tok).cpu()
    pred = E_corr > thr
    tp = float((pred & true_corrupt).sum())
    fp = float((pred & ~true_corrupt).sum())
    fn = float((~pred & true_corrupt).sum())
    prec = tp / max(tp + fp, 1.0)
    rec = tp / max(tp + fn, 1.0)
    f1 = 2 * prec * rec / max(prec + rec, 1e-9)
    return thr, {"threshold": thr, "precision": prec, "recall": rec, "f1": f1,
                 "target_fpr": target_fpr}


# --------------------------------------------------------------------------- #
# Inpainter: masked-Euler integration of the DirichletFM marginal field.
# --------------------------------------------------------------------------- #
@torch.no_grad()
def inpaint(model, observed_ids, heal_mask, *, nfe, device, chunk=16):
    """Heal flagged positions while pinning trusted ones.

    observed_ids : (B, L) long — the corrupted text we observe.
    heal_mask    : (B, L) bool — True = suspected corrupt (generate); False = trust.
    Integrates t: 1 -> t_max. Trusted positions are re-imposed every step via the
    deterministic Dirichlet mean concentrated (∝ t) on the observed token; flagged
    positions evolve under the marginal vector field. Returns healed token ids.
    Sequences are independent under the field, so a large demo batch is processed
    in sub-batches of ``chunk`` to bound GPU memory (exact, not an approximation)."""
    if observed_ids.shape[0] > chunk:
        parts = [
            inpaint(model, observed_ids[i:i + chunk], heal_mask[i:i + chunk],
                    nfe=nfe, device=device, chunk=chunk)
            for i in range(0, observed_ids.shape[0], chunk)
        ]
        return torch.cat(parts, 0)
    dfm = model.dfm
    K = model.K
    t_max = float(dfm.t_max)
    B, L = observed_ids.shape
    obs = observed_ids.to(device).long()
    m = heal_mask.to(device).bool().unsqueeze(-1).float()  # (B,L,1): 1=heal

    def dir_mean(t_scalar):
        """Deterministic mean of Dir(beta(t, obs)): beta/sum, beta=1 + (t-1)·e_obs."""
        beta = torch.ones(B, L, K, device=device)
        beta.scatter_(-1, obs.unsqueeze(-1), float(t_scalar))
        return beta / beta.sum(-1, keepdim=True)

    x = torch.full((B, L, K), 1.0 / K, device=device)  # t=1 => uniform everywhere
    t_grid = torch.linspace(1.0, t_max, nfe + 1, device=device)
    for i in range(nfe):
        t = float(t_grid[i].item())
        dt = float((t_grid[i + 1] - t_grid[i]).item())
        x = m * x + (1.0 - m) * dir_mean(t)  # re-impose trusted positions

        t_batch = torch.full((B,), t, device=device, dtype=x.dtype)
        logits = model.forward(x, t_batch)        # wrapper -> dfm.forward (normalises t)
        p1 = logits.softmax(dim=-1)

        x_clamped = x.clamp(min=1e-6, max=1.0 - 1e-6)
        c_dot = _conditional_velocity_factor(x_clamped, t, K)
        denom = (1.0 - x_clamped).clamp(min=1e-6)
        w = p1 * c_dot / denom
        v = w - x * w.sum(dim=-1, keepdim=True)   # marginal field (DirichletFM Thm 3.1)

        x = (x + dt * v).clamp(min=1e-6)
        x = x / x.sum(dim=-1, keepdim=True)

    healed = x.argmax(dim=-1).cpu()
    trust = ~heal_mask.cpu().bool()
    healed[trust] = observed_ids.cpu()[trust]  # trusted tokens never change
    return healed


def score_healing(clean_t, corr_t, healed_t, heal_mask, true_corrupt):
    """Per-token scoring of a heal result vs the clean ground truth.

    Returns rates AND raw counts so multiple seeds can be POOLED (sum counts)
    rather than averaging ratios. ``delta_wholeseq`` is bounded by corrupt_rate
    (most positions are restored verbatim) — fix_rate/damage_rate are the headline.
    """
    clean, corr, heal = clean_t.cpu(), corr_t.cpu(), healed_t.cpu()
    tc, pred = true_corrupt.cpu(), heal_mask.cpu()
    n_corrupt = int(tc.sum())
    n_clean = int((~tc).sum())
    n_fixed = int(((heal == clean) & tc).sum())
    n_damaged = int(((heal != clean) & ~tc).sum())
    tp = int((pred & tc).sum())
    fp = int((pred & ~tc).sum())
    fn = int((~pred & tc).sum())
    acc_corr = float((corr == clean).float().mean())
    acc_heal = float((heal == clean).float().mean())
    return {
        "n_corrupt": n_corrupt, "n_clean": n_clean,
        "n_fixed": n_fixed, "n_damaged": n_damaged,
        "tp": tp, "fp": fp, "fn": fn,
        "fix_rate": n_fixed / max(n_corrupt, 1),
        "damage_rate": n_damaged / max(n_clean, 1),
        "net_per_corrupt": (n_fixed - n_damaged) / max(n_corrupt, 1),
        "acc_corrupted": acc_corr, "acc_healed": acc_heal,
        "delta_wholeseq": acc_heal - acc_corr,
    }


def uq_report(uq_score, demo_clean, sel_artifacts):
    """Calibrated-uncertainty report for the valid-only GP variance channel.

    Pools the selected-operating-point seeds and answers three questions that a
    discriminative localizer cannot:
      • detection    — does pre-heal variance separate corrupt from clean tokens?
      • OOD-reduction — does healing pull corrupt-position variance back toward
                        the clean level (the heal genuinely de-OODs the text)?
      • heal-confidence — does *residual* (post-heal) variance flag the corrupt
                        positions the heal failed to fix? (high var == still OOD)
    """
    clean = demo_clean.cpu()
    Vc_l, Vh_l, tc_l, fixed_l, flag_l = [], [], [], [], []
    V_clean = uq_score(demo_clean).cpu()
    for dc, mask, healed in sel_artifacts:
        dc, healed = dc.cpu(), healed.cpu()
        Vc_l.append(uq_score(dc).cpu())
        Vh_l.append(uq_score(healed).cpu())
        tc_l.append(dc != clean)
        fixed_l.append(healed == clean)
        flag_l.append(mask.cpu().bool())
    Vc, Vh = torch.cat(Vc_l), torch.cat(Vh_l)
    tc, fixed, flag = torch.cat(tc_l), torch.cat(fixed_l), torch.cat(flag_l)
    cf, cu = tc & fixed, tc & ~fixed   # corrupt-and-fixed / corrupt-and-unfixed
    # Flagged-only: removes the trivial confound that UNflagged corrupt tokens
    # are never healed -> always "unfixed". On flagged corrupt tokens the heal
    # actually ran, so variance predicting unfixed here is genuine heal-difficulty.
    cf_fl, cu_fl = cf & flag, cu & flag

    def _au(pos, neg):
        return _auroc(pos, neg) if pos.numel() and neg.numel() else float("nan")

    return {
        "var_clean_mean": float(V_clean.mean()),
        "var_corrupt_pos_pre": float(Vc[tc].mean()) if tc.any() else float("nan"),
        "var_corrupt_pos_post": float(Vh[tc].mean()) if tc.any() else float("nan"),
        "var_clean_pos_post": float(Vh[~tc].mean()),
        "auroc_detect_pre": _au(Vc[tc], Vc[~tc]),
        "auroc_resid_flags_unfixed": _au(Vh[cu], Vh[cf]),
        "auroc_preheal_predicts_unfixed": _au(Vc[cu], Vc[cf]),
        # confound-controlled (flagged corrupt tokens only — the heal actually ran)
        "auroc_resid_flags_unfixed_flaggedonly": _au(Vh[cu_fl], Vh[cf_fl]),
        "auroc_preheal_predicts_unfixed_flaggedonly": _au(Vc[cu_fl], Vc[cf_fl]),
        "n_corrupt": int(tc.sum()), "n_fixed": int(cf.sum()), "n_unfixed": int(cu.sum()),
        "n_flagged_fixed": int(cf_fl.sum()), "n_flagged_unfixed": int(cu_fl.sum()),
    }


def aggregate(ms):
    """Pool per-seed score dicts: sum counts (proper denominators), std over seeds."""
    F = sum(m["n_fixed"] for m in ms)
    C = sum(m["n_corrupt"] for m in ms)
    D = sum(m["n_damaged"] for m in ms)
    N = sum(m["n_clean"] for m in ms)
    tp = sum(m["tp"] for m in ms)
    fp = sum(m["fp"] for m in ms)
    fn = sum(m["fn"] for m in ms)
    nets = [m["net_per_corrupt"] for m in ms]
    deltas = [m["delta_wholeseq"] for m in ms]
    net_sd = statistics.pstdev(nets) if len(nets) > 1 else 0.0
    delta_sd = statistics.pstdev(deltas) if len(deltas) > 1 else 0.0
    return {
        "n_seeds": len(ms),
        "fix_rate": F / max(C, 1), "damage_rate": D / max(N, 1),
        "net_per_corrupt": (F - D) / max(C, 1), "net_per_corrupt_std": net_sd,
        "loc_precision": tp / max(tp + fp, 1), "loc_recall": tp / max(tp + fn, 1),
        "delta_wholeseq": sum(deltas) / len(deltas), "delta_wholeseq_std": delta_sd,
        "n_corrupt_total": C, "n_fixed_total": F, "n_damaged_total": D,
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--ckpt", required=True)
    ap.add_argument("--out", default="heal_out/heal.json")
    ap.add_argument("--t-eval", type=float, default=None,
                    help="Dirichlet path-time for feature extraction (default cfg ~4.5)")
    ap.add_argument("--fit-seqs", type=int, default=256,
                    help="# clean sequences to train the localizer head")
    ap.add_argument("--n-demo", type=int, default=16, help="# sequences to corrupt & heal")
    ap.add_argument("--n-seeds", type=int, default=5,
                    help="# independent demo-corruption realizations to average")
    ap.add_argument("--corrupt-rate", type=float, default=0.15,
                    help="substitution rate for the demo passage (the 'unknown' corruption)")
    ap.add_argument("--train-rate", type=float, default=0.3,
                    help="corruption rate for the localizer's training negatives")
    ap.add_argument("--target-fprs", type=str, default="0.02,0.05,0.10",
                    help="comma list of clean-token FPR targets to sweep (mask tightness)")
    ap.add_argument("--margin", type=float, default=4.0)
    ap.add_argument("--head-steps", type=int, default=600)
    ap.add_argument("--lr", type=float, default=5e-2)
    ap.add_argument("--nfe", type=int, default=100, help="Euler steps for inpainting")
    ap.add_argument("--seed", type=int, default=42)
    ap.add_argument("--split", choices=["train", "val", "test"], default="val",
                    help="dataset split for fit/cal/demo sequences "
                         "(test = held-out last-5M text8 split)")
    # --- localizer choice: linear hinge head (default) or post-hoc SVGP head ---
    ap.add_argument("--localizer", choices=["linear", "gp", "nll"], default="linear",
                    help="per-token corruption localizer: 'linear' (BayesLin hinge), "
                         "'gp' (post-hoc SVGP energy+variance auditor), or 'nll' "
                         "(training-free denoiser surprise at --t-nll)")
    ap.add_argument("--t-nll", type=float, default=3.0,
                    help="[nll] path-time for the denoiser-NLL localizer (low/context "
                         "regime, ~3); see scripts/ood_denoiser_nll.py")
    ap.add_argument("--gp-mode", choices=["oneclass", "contrastive"], default="oneclass",
                    help="[gp] 'oneclass' = SVGP fit on valid data only, OOD=variance "
                         "(recommended); 'contrastive' = energy hinge on corrupt negatives")
    ap.add_argument("--gp-d-latent", type=int, default=0,
                    help="[gp] deep-kernel projection dim (0 = identity / raw features, "
                         "the BLR-comparable choice)")
    ap.add_argument("--gp-num-inducing", type=int, default=256, help="[gp] inducing points")
    ap.add_argument("--gp-steps", type=int, default=1500, help="[gp] SVGP training steps")
    ap.add_argument("--gp-lr", type=float, default=1e-2, help="[gp] SVGP LR")
    ap.add_argument("--gp-batch", type=int, default=4096, help="[gp] per-step token minibatch")
    ap.add_argument("--gp-lengthscale-scale", type=float, default=0.1,
                    help="[gp] lengthscale = sqrt(d_latent)*scale; small => sharp variance "
                         "contrast off-manifold (0.1 best in sweep)")
    ap.add_argument("--gp-learn-lengthscale", action="store_true",
                    help="[gp] learn the lengthscale (default: small & fixed)")
    ap.add_argument("--gp-noise-init", type=float, default=0.1,
                    help="[gp/oneclass] initial regression noise sigma^2")
    ap.add_argument("--gp-margin-var", type=float, default=1.0,
                    help="[gp/contrastive] variance-hinge margin")
    ap.add_argument("--gp-lambda-var", type=float, default=0.5,
                    help="[gp/contrastive] variance-hinge weight")
    ap.add_argument("--gp-lambda-kl", type=float, default=0.01, help="[gp] SVGP KL weight")
    ap.add_argument("--gp-var-weights", type=str, default="0,0.5,1,2,4",
                    help="[gp] candidate channel-combine weights (GT-free selected on fit)")
    # --- hybrid UQ channel: valid-only one-class GP variance, reported alongside ---
    ap.add_argument("--uq", choices=["none", "gp_variance"], default="none",
                    help="add a one-class GP-variance calibrated-uncertainty channel (fit on "
                         "VALID data only) reported alongside the heal: standalone detection, "
                         "OOD-reduction by healing, and residual-variance heal-confidence")
    args = ap.parse_args()

    torch.manual_seed(args.seed)
    np.random.seed(args.seed)
    device = "cuda" if torch.cuda.is_available() else "cpu"
    model, cfg = _load_dirichletfm(args.ckpt, device)
    K = cfg.text8_dataset.K
    L = cfg.text8_dataset.L
    t_eval = float(args.t_eval if args.t_eval is not None else cfg.dfm_svgp.t_eval)
    print(f"[heal] ckpt={args.ckpt}")
    print(f"[heal] K={K} L={L} t_max={model.dfm.t_max} t_eval={t_eval} device={device}")

    dm, _ = build_training_datamodule(cfg)
    _split_loaders = {"train": dm.train_dataloader, "val": dm.val_dataloader,
                      "test": dm.test_dataloader}
    vl = _split_loaders[args.split]() or dm.train_dataloader()
    need = 2 * args.fit_seqs + args.n_demo
    seqs = []
    for b in vl:
        seqs.append(b["token_ids"].long())
        if sum(s.shape[0] for s in seqs) >= need:
            break
    seqs = torch.cat(seqs)
    if seqs.shape[0] < need:
        raise SystemExit(
            f"val loader yielded {seqs.shape[0]} seqs < required {need} "
            f"(2*fit_seqs + n_demo); lower --fit-seqs/--n-demo"
        )
    fit_tok = seqs[: args.fit_seqs]
    cal_tok = seqs[args.fit_seqs : 2 * args.fit_seqs]
    demo_clean = seqs[2 * args.fit_seqs : 2 * args.fit_seqs + args.n_demo]
    print(f"[heal] disjoint splits: fit={fit_tok.shape[0]} cal={cal_tok.shape[0]} "
          f"demo={demo_clean.shape[0]}  n_seeds={args.n_seeds}")

    # ---- 1. localizer ----
    print(f"=== build per-token localizer ({args.localizer}) ===")
    if args.localizer == "nll":
        t_max_chk = float(model.dfm.t_max)
        if not (1.0 <= args.t_nll <= t_max_chk):
            raise SystemExit(f"--t-nll={args.t_nll} must lie in [1, t_max={t_max_chk}]")
        print(f"  [nll] training-free denoiser-surprise localizer @ t_nll={args.t_nll} "
              f"(no head, no fit set)")
        score, d = make_nll_localizer(model, args.t_nll, device)
    elif args.localizer == "gp":
        var_weights = [float(x) for x in args.gp_var_weights.split(",") if x.strip()]
        score, d = train_gp_localizer(
            model, fit_tok, t_eval, device, mode=args.gp_mode, train_rate=args.train_rate,
            margin=args.margin, steps=args.gp_steps, lr=args.gp_lr, seed=args.seed,
            d_latent=args.gp_d_latent, num_inducing=args.gp_num_inducing,
            margin_var=args.gp_margin_var, lambda_var=args.gp_lambda_var,
            lambda_kl=args.gp_lambda_kl, batch=args.gp_batch, var_weights=var_weights,
            lengthscale_scale=args.gp_lengthscale_scale,
            learn_lengthscale=args.gp_learn_lengthscale, noise_init=args.gp_noise_init,
        )
    else:
        score, d = train_localizer(
            model, fit_tok, t_eval, device, train_rate=args.train_rate,
            margin=args.margin, steps=args.head_steps, lr=args.lr, seed=args.seed,
        )

    # ---- 1b. UQ channel: valid-only one-class GP variance head (independent of
    #         the localizer). Its score(tok) returns the per-token predictive
    #         variance (Matern analog of BLR's one-class Mahalanobis density). ----
    uq_score = None
    if args.uq == "gp_variance":
        print("=== train one-class GP variance UQ head (valid data only) ===")
        uq_score, _ = train_gp_localizer(
            model, fit_tok, t_eval, device, mode="oneclass", train_rate=args.corrupt_rate,
            margin=args.margin, steps=args.gp_steps, lr=args.gp_lr, seed=args.seed,
            d_latent=args.gp_d_latent, num_inducing=max(512, args.gp_num_inducing),
            margin_var=args.gp_margin_var, lambda_var=args.gp_lambda_var,
            lambda_kl=args.gp_lambda_kl, batch=args.gp_batch, var_weights=[0.0],
            lengthscale_scale=args.gp_lengthscale_scale,
            learn_lengthscale=args.gp_learn_lengthscale, noise_init=0.05,
        )

    # ---- 2. thresholds + GT-FREE operating-point selection (max cal-set F1) ----
    cal_corr = corrupt_token_ids(
        cal_tok.clone(), vocab_size=K, corrupt_rate=args.corrupt_rate, seed=args.seed + 1
    )
    fprs = [float(x) for x in args.target_fprs.split(",") if x.strip()]
    thr_by_fpr = {}
    for fpr in fprs:
        thr, cal_stats = calibrate_threshold(score, cal_tok, cal_corr, target_fpr=fpr)
        thr_by_fpr[fpr] = (thr, cal_stats)
    sel_fpr = max(fprs, key=lambda f: thr_by_fpr[f][1]["f1"])  # GT-free (cal set only)

    # ---- 3. demo: corrupt over n_seeds, localize (energy only), inpaint, score ----
    print(f"=== heal sweep (mean over {args.n_seeds} corruption seeds) ===")
    print(f"{'fpr':>5} {'thr':>7} {'loc_P':>6} {'loc_R':>6} {'fix':>6} {'dmg':>6} "
          f"{'net/corrupt':>14} {'delta_ws':>10}")
    demo_corrs = [
        corrupt_token_ids(demo_clean.clone(), vocab_size=K,
                          corrupt_rate=args.corrupt_rate, seed=args.seed + 100 + s)
        for s in range(args.n_seeds)
    ]
    E_demos = [score(dc) for dc in demo_corrs]  # per-token energy; GT never used here

    sweep = []
    example = None
    sel_artifacts = []  # per-seed (dc, mask, healed) at the selected operating point
    for fpr in fprs:
        thr, cal_stats = thr_by_fpr[fpr]
        per_seed = []
        first_artifacts = None
        for s in range(args.n_seeds):
            dc = demo_corrs[s]
            mask = E_demos[s] > thr
            healed = inpaint(model, dc, mask, nfe=args.nfe, device=device)
            m = score_healing(demo_clean, dc, healed, mask, dc != demo_clean)
            per_seed.append(m)
            if s == 0:
                first_artifacts = (dc, mask, healed)
            if fpr == sel_fpr:
                sel_artifacts.append((dc, mask, healed))
        agg = aggregate(per_seed)
        tag = "  <- selected" if fpr == sel_fpr else ""
        print(f"{fpr:>5.2f} {thr:>7.3f} {agg['loc_precision']:>6.3f} "
              f"{agg['loc_recall']:>6.3f} {agg['fix_rate']:>6.3f} {agg['damage_rate']:>6.3f} "
              f"{agg['net_per_corrupt']:>+8.3f}±{agg['net_per_corrupt_std']:.3f} "
              f"{agg['delta_wholeseq']:>+10.4f}{tag}")
        sweep.append({"target_fpr": fpr, "threshold": thr, "calibration": cal_stats, **agg})
        if fpr == sel_fpr:
            example = first_artifacts

    # ---- 4. example dump from the SELECTED (cal-F1) operating point, seed 0 ----
    dc0, mask0, healed0 = example
    clean = demo_clean.cpu()
    print(f"\n--- example[0] @ selected fpr={sel_fpr} (chosen by cal-set F1) ---")
    print(f"  clean : {_decode(clean[0])!r}")
    print(f"  corr  : {_decode(dc0.cpu()[0])!r}")
    print(f"  truec : {''.join('^' if x else ' ' for x in (dc0.cpu()[0] != clean[0]).tolist())}")
    print(f"  flag  : {''.join('*' if x else ' ' for x in mask0.cpu()[0].tolist())}")
    print(f"  healed: {_decode(healed0.cpu()[0])!r}")

    sel = next(r for r in sweep if r["target_fpr"] == sel_fpr)
    print(f"\n=== HEADLINE @ selected fpr={sel_fpr} (mean±std over {args.n_seeds} seeds) ===")
    print(f"  fix_rate    = {sel['fix_rate']:.3f}   (corrupt token -> correct)")
    print(f"  damage_rate = {sel['damage_rate']:.3f}   (clean token -> broken)")
    print(f"  net/corrupt = {sel['net_per_corrupt']:+.3f} ± {sel['net_per_corrupt_std']:.3f}"
          f"   (net tokens recovered per corrupt token; >0 ⇒ net benefit)")
    print(f"  delta_ws    = {sel['delta_wholeseq']:+.4f} ± {sel['delta_wholeseq_std']:.4f}"
          f"   (whole-seq; diluted, capped near corrupt_rate — diagnostic only)")

    uq = None
    if uq_score is not None:
        uq = uq_report(uq_score, demo_clean, sel_artifacts)
        print(f"\n=== UQ channel (valid-only one-class GP variance) @ fpr={sel_fpr} ===")
        print(f"  variance  clean={uq['var_clean_mean']:.3f}  "
              f"corrupt(pre-heal)={uq['var_corrupt_pos_pre']:.3f}  "
              f"corrupt(post-heal)={uq['var_corrupt_pos_post']:.3f}  "
              f"-> healing {'reduces' if uq['var_corrupt_pos_post'] < uq['var_corrupt_pos_pre'] else 'raises'} OOD variance")
        print(f"  AUROC detect (pre-heal corrupt vs clean) : {uq['auroc_detect_pre']:.3f}")
        print(f"  AUROC residual-variance flags UNFIXED    : {uq['auroc_resid_flags_unfixed']:.3f}"
              f"   (heal-confidence: high post-heal var == still corrupt)")
        print(f"  AUROC pre-heal var predicts UNFIXED      : {uq['auroc_preheal_predicts_unfixed']:.3f}")
        print(f"  [confound-controlled, flagged corrupt only]")
        print(f"    AUROC residual flags UNFIXED           : {uq['auroc_resid_flags_unfixed_flaggedonly']:.3f}")
        print(f"    AUROC pre-heal predicts UNFIXED        : {uq['auroc_preheal_predicts_unfixed_flaggedonly']:.3f}"
              f"   (n_flagged fixed/unfixed = {uq['n_flagged_fixed']}/{uq['n_flagged_unfixed']})")

    rows = {
        "ckpt": args.ckpt, "K": K, "L": L, "t_max": float(model.dfm.t_max),
        "localizer": args.localizer,
        "gp_mode": (args.gp_mode if args.localizer == "gp" else None),
        "t_nll": (args.t_nll if args.localizer == "nll" else None),
        "uq": (args.uq if args.uq != "none" else None), "uq_report": uq,
        "t_eval": t_eval, "d_model": d, "nfe": args.nfe, "n_seeds": args.n_seeds,
        "corrupt_rate": args.corrupt_rate, "train_rate": args.train_rate,
        "n_demo": int(demo_clean.shape[0]),
        "selected_fpr": sel_fpr, "selection": "max cal-set F1 (GT-free on demo)",
        "sweep": sweep,
        "examples": [
            {
                "clean": _decode(clean[b]), "corrupted": _decode(dc0.cpu()[b]),
                "healed": _decode(healed0.cpu()[b]),
                "true_corrupt": [bool(x) for x in (dc0.cpu()[b] != clean[b]).tolist()],
                "flagged": [bool(x) for x in mask0.cpu()[b].tolist()],
            }
            for b in range(min(4, demo_clean.shape[0]))
        ],
    }
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(rows, indent=2))
    print(f"\nWrote {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
