"""Heal corrupted text with DirichletFM — approach C (localize-then-inpaint).

End-to-end "self-healing" inference on a FROZEN DirichletFM checkpoint, for the
realistic setting where **we do not know which tokens are corrupted**. One
backbone serves two roles (no new network is trained beyond a single linear
head):

  1. LOCALIZE — a per-token linear *energy* head on frozen DirichletFM features
     (the BayesLinHead recipe, ``scripts/ood_bayes_linear.py``): valid char -> E~0,
     corrupt char -> E>=margin. Features are the DETERMINISTIC Dirichlet-mean
     backbone activations at ``t_eval`` (``_perpos_feats``). Per-token energy is
     thresholded into a binary heal-mask; the threshold is calibrated to a target
     false-positive rate on clean tokens, and the headline operating point is
     selected by F1 on the held-out CALIBRATION set (never on the demo).

  2. INPAINT — a masked-Euler integration of the DirichletFM marginal vector
     field (``t: 1 -> t_max``). Trusted (un-flagged) positions are re-imposed
     every step via the deterministic Dirichlet mean concentrated on the observed
     token (RePaint-style known-region conditioning, adapted to the Dirichlet
     path); flagged positions are generated by the field, conditioned on the
     trusted context through the non-causal backbone. Trusted tokens are restored
     verbatim at the end.

The ground-truth corruption mask is used ONLY to *score* the demo result — never
to drive healing or to select the operating point. The demo corruption is
averaged over ``--n-seeds`` independent realizations to give an honest CI.

Headline metrics (per-region, correctly denominated):
  fix_rate     = P(corrupt token -> correct)           [recovery, want high]
  damage_rate  = P(clean token   -> broken)            [collateral, want low]
  net/corrupt  = (fixed - damaged) / n_corrupt          [net tokens recovered per corrupt]
The whole-sequence delta is reported only as a (dilution-dominated) diagnostic:
it equals (fixed - damaged)/(B*L) and is structurally capped near corrupt_rate
because ~(1-corrupt_rate) of positions are restored verbatim.

Honest ceiling: this is character-level text8. Healing moves toward
n-gram-plausible character strings, not toward correct words/meaning. It is a
*mechanism demonstration* of transport-based, OOD-localized healing.

Usage:
    python scripts/heal_dirichlet.py \
        --ckpt runs/sflm_bench_a100_20g_L256_d1280L14_full/DirichletFM/epoch_final.pt \
        --corrupt-rate 0.15 --n-demo 16 --n-seeds 5 --out heal_out/heal.json
"""

from __future__ import annotations

import argparse
import json
import statistics
import sys
from pathlib import Path

import numpy as np
import torch
import torch.nn as nn


def _bootstrap() -> None:
    repo_root = Path(__file__).resolve().parent.parent
    src = repo_root / "src"
    if str(src) not in sys.path:
        sys.path.insert(0, str(src))
    if str(repo_root) not in sys.path:
        sys.path.append(str(repo_root))


_bootstrap()

from scripts.ood_variance_perpos import _load_dirichletfm, _perpos_feats  # noqa: E402
from aitchinson_flow.training import build_training_datamodule  # noqa: E402
from aitchinson_flow.data.corruption import corrupt_token_ids  # noqa: E402
from aitchinson_flow.models.dirichlet_fm import (  # noqa: E402
    _conditional_velocity_factor,
)

_ALPH = "abcdefghijklmnopqrstuvwxyz "  # text8 K=27 decode (a-z + space)


def _decode(ids) -> str:
    return "".join(_ALPH[int(i)] if int(i) < len(_ALPH) else "?" for i in ids)


# --------------------------------------------------------------------------- #
# Localizer: per-token linear energy head on frozen DirichletFM features.
# --------------------------------------------------------------------------- #
def train_localizer(model, fit_tok, t_eval, device, *, train_rate, margin, steps, lr, seed):
    """Train the per-token energy head + standardiser on clean/corrupt features.

    Returns a ``score(token_ids) -> E_t (B,L)`` closure. Mirrors the energy-head
    half of ``scripts/ood_bayes_linear.py`` (raw d_model features, no PCA, no
    Laplace variance)."""
    K = model.K
    fc = _perpos_feats(model, fit_tok, t_eval, device)  # (Nf, L, d) clean
    d = fc.shape[-1]
    corr_tok = corrupt_token_ids(
        fit_tok.clone(), vocab_size=K, corrupt_rate=train_rate, seed=seed
    )
    fk = _perpos_feats(model, corr_tok, t_eval, device)  # (Nf, L, d) corrupted
    label_corr = (corr_tok != fit_tok).reshape(-1)  # (Nf*L,) bool

    mu = fc.reshape(-1, d).mean(0)
    sigma = fc.reshape(-1, d).std(0).clamp_min(1e-6)

    def _proj(h_flat):
        m, s = mu.to(h_flat.device), sigma.to(h_flat.device)
        return (h_flat - m) / s

    zc = _proj(fc.reshape(-1, d)).to(device)
    zk = _proj(fk.reshape(-1, d)).to(device)
    yk = label_corr.to(device)

    head = nn.Linear(d, 1).to(device)
    opt = torch.optim.Adam(head.parameters(), lr=lr)
    zpos = torch.cat([zc, zk[~yk]], 0)  # valid chars (clean + unchanged-corrupt)
    zneg = zk[yk]                       # corrupted chars
    for step in range(steps):
        opt.zero_grad()
        ep = head(zpos).squeeze(-1)
        en = head(zneg).squeeze(-1)
        loss = ep.pow(2).mean() + torch.relu(margin - en).mean()
        loss.backward()
        opt.step()
        if step % 200 == 0 or step == steps - 1:
            print(f"  [head] step {step:4d}  E_valid={ep.mean():+.3f}  "
                  f"E_corrupt={en.mean():+.3f}  gap={(en.mean() - ep.mean()):+.3f}")
    head.eval()

    @torch.no_grad()
    def score(tok):
        h = _perpos_feats(model, tok, t_eval, device)  # (B, L, d)
        b, Lq, _ = h.shape
        z = _proj(h.reshape(-1, d)).to(device)
        return head(z).squeeze(-1).reshape(b, Lq).cpu()  # (B, L)

    return score, d


def calibrate_threshold(score, clean_tok, corrupt_tok, *, target_fpr):
    """Threshold giving ~target_fpr on clean tokens; report its precision/recall/F1
    on the held-out calibration corrupt batch (used for GT-free operating-point
    selection)."""
    E_clean = score(clean_tok).reshape(-1)
    thr = float(torch.quantile(E_clean, 1.0 - target_fpr))
    E_corr = score(corrupt_tok)
    true_corrupt = (corrupt_tok != clean_tok).cpu()
    pred = E_corr > thr
    tp = float((pred & true_corrupt).sum())
    fp = float((pred & ~true_corrupt).sum())
    fn = float((~pred & true_corrupt).sum())
    prec = tp / max(tp + fp, 1.0)
    rec = tp / max(tp + fn, 1.0)
    f1 = 2 * prec * rec / max(prec + rec, 1e-9)
    return thr, {"threshold": thr, "precision": prec, "recall": rec, "f1": f1,
                 "target_fpr": target_fpr}


# --------------------------------------------------------------------------- #
# Inpainter: masked-Euler integration of the DirichletFM marginal field.
# --------------------------------------------------------------------------- #
@torch.no_grad()
def inpaint(model, observed_ids, heal_mask, *, nfe, device):
    """Heal flagged positions while pinning trusted ones.

    observed_ids : (B, L) long — the corrupted text we observe.
    heal_mask    : (B, L) bool — True = suspected corrupt (generate); False = trust.
    Integrates t: 1 -> t_max. Trusted positions are re-imposed every step via the
    deterministic Dirichlet mean concentrated (∝ t) on the observed token; flagged
    positions evolve under the marginal vector field. Returns healed token ids."""
    dfm = model.dfm
    K = model.K
    t_max = float(dfm.t_max)
    B, L = observed_ids.shape
    obs = observed_ids.to(device).long()
    m = heal_mask.to(device).bool().unsqueeze(-1).float()  # (B,L,1): 1=heal

    def dir_mean(t_scalar):
        """Deterministic mean of Dir(beta(t, obs)): beta/sum, beta=1 + (t-1)·e_obs."""
        beta = torch.ones(B, L, K, device=device)
        beta.scatter_(-1, obs.unsqueeze(-1), float(t_scalar))
        return beta / beta.sum(-1, keepdim=True)

    x = torch.full((B, L, K), 1.0 / K, device=device)  # t=1 => uniform everywhere
    t_grid = torch.linspace(1.0, t_max, nfe + 1, device=device)
    for i in range(nfe):
        t = float(t_grid[i].item())
        dt = float((t_grid[i + 1] - t_grid[i]).item())
        x = m * x + (1.0 - m) * dir_mean(t)  # re-impose trusted positions

        t_batch = torch.full((B,), t, device=device, dtype=x.dtype)
        logits = model.forward(x, t_batch)        # wrapper -> dfm.forward (normalises t)
        p1 = logits.softmax(dim=-1)

        x_clamped = x.clamp(min=1e-6, max=1.0 - 1e-6)
        c_dot = _conditional_velocity_factor(x_clamped, t, K)
        denom = (1.0 - x_clamped).clamp(min=1e-6)
        w = p1 * c_dot / denom
        v = w - x * w.sum(dim=-1, keepdim=True)   # marginal field (DirichletFM Thm 3.1)

        x = (x + dt * v).clamp(min=1e-6)
        x = x / x.sum(dim=-1, keepdim=True)

    healed = x.argmax(dim=-1).cpu()
    trust = ~heal_mask.cpu().bool()
    healed[trust] = observed_ids.cpu()[trust]  # trusted tokens never change
    return healed


def score_healing(clean_t, corr_t, healed_t, heal_mask, true_corrupt):
    """Per-token scoring of a heal result vs the clean ground truth.

    Returns rates AND raw counts so multiple seeds can be POOLED (sum counts)
    rather than averaging ratios. ``delta_wholeseq`` is bounded by corrupt_rate
    (most positions are restored verbatim) — fix_rate/damage_rate are the headline.
    """
    clean, corr, heal = clean_t.cpu(), corr_t.cpu(), healed_t.cpu()
    tc, pred = true_corrupt.cpu(), heal_mask.cpu()
    n_corrupt = int(tc.sum())
    n_clean = int((~tc).sum())
    n_fixed = int(((heal == clean) & tc).sum())
    n_damaged = int(((heal != clean) & ~tc).sum())
    tp = int((pred & tc).sum())
    fp = int((pred & ~tc).sum())
    fn = int((~pred & tc).sum())
    acc_corr = float((corr == clean).float().mean())
    acc_heal = float((heal == clean).float().mean())
    return {
        "n_corrupt": n_corrupt, "n_clean": n_clean,
        "n_fixed": n_fixed, "n_damaged": n_damaged,
        "tp": tp, "fp": fp, "fn": fn,
        "fix_rate": n_fixed / max(n_corrupt, 1),
        "damage_rate": n_damaged / max(n_clean, 1),
        "net_per_corrupt": (n_fixed - n_damaged) / max(n_corrupt, 1),
        "acc_corrupted": acc_corr, "acc_healed": acc_heal,
        "delta_wholeseq": acc_heal - acc_corr,
    }


def aggregate(ms):
    """Pool per-seed score dicts: sum counts (proper denominators), std over seeds."""
    F = sum(m["n_fixed"] for m in ms)
    C = sum(m["n_corrupt"] for m in ms)
    D = sum(m["n_damaged"] for m in ms)
    N = sum(m["n_clean"] for m in ms)
    tp = sum(m["tp"] for m in ms)
    fp = sum(m["fp"] for m in ms)
    fn = sum(m["fn"] for m in ms)
    nets = [m["net_per_corrupt"] for m in ms]
    deltas = [m["delta_wholeseq"] for m in ms]
    net_sd = statistics.pstdev(nets) if len(nets) > 1 else 0.0
    delta_sd = statistics.pstdev(deltas) if len(deltas) > 1 else 0.0
    return {
        "n_seeds": len(ms),
        "fix_rate": F / max(C, 1), "damage_rate": D / max(N, 1),
        "net_per_corrupt": (F - D) / max(C, 1), "net_per_corrupt_std": net_sd,
        "loc_precision": tp / max(tp + fp, 1), "loc_recall": tp / max(tp + fn, 1),
        "delta_wholeseq": sum(deltas) / len(deltas), "delta_wholeseq_std": delta_sd,
        "n_corrupt_total": C, "n_fixed_total": F, "n_damaged_total": D,
    }


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--ckpt", required=True)
    ap.add_argument("--out", default="heal_out/heal.json")
    ap.add_argument("--t-eval", type=float, default=None,
                    help="Dirichlet path-time for feature extraction (default cfg ~4.5)")
    ap.add_argument("--fit-seqs", type=int, default=256,
                    help="# clean sequences to train the localizer head")
    ap.add_argument("--n-demo", type=int, default=16, help="# sequences to corrupt & heal")
    ap.add_argument("--n-seeds", type=int, default=5,
                    help="# independent demo-corruption realizations to average")
    ap.add_argument("--corrupt-rate", type=float, default=0.15,
                    help="substitution rate for the demo passage (the 'unknown' corruption)")
    ap.add_argument("--train-rate", type=float, default=0.3,
                    help="corruption rate for the localizer's training negatives")
    ap.add_argument("--target-fprs", type=str, default="0.02,0.05,0.10",
                    help="comma list of clean-token FPR targets to sweep (mask tightness)")
    ap.add_argument("--margin", type=float, default=4.0)
    ap.add_argument("--head-steps", type=int, default=600)
    ap.add_argument("--lr", type=float, default=5e-2)
    ap.add_argument("--nfe", type=int, default=100, help="Euler steps for inpainting")
    ap.add_argument("--seed", type=int, default=42)
    args = ap.parse_args()

    torch.manual_seed(args.seed)
    np.random.seed(args.seed)
    device = "cuda" if torch.cuda.is_available() else "cpu"
    model, cfg = _load_dirichletfm(args.ckpt, device)
    K = cfg.text8_dataset.K
    L = cfg.text8_dataset.L
    t_eval = float(args.t_eval if args.t_eval is not None else cfg.dfm_svgp.t_eval)
    print(f"[heal] ckpt={args.ckpt}")
    print(f"[heal] K={K} L={L} t_max={model.dfm.t_max} t_eval={t_eval} device={device}")

    dm, _ = build_training_datamodule(cfg)
    vl = dm.val_dataloader() or dm.train_dataloader()
    need = 2 * args.fit_seqs + args.n_demo
    seqs = []
    for b in vl:
        seqs.append(b["token_ids"].long())
        if sum(s.shape[0] for s in seqs) >= need:
            break
    seqs = torch.cat(seqs)
    if seqs.shape[0] < need:
        raise SystemExit(
            f"val loader yielded {seqs.shape[0]} seqs < required {need} "
            f"(2*fit_seqs + n_demo); lower --fit-seqs/--n-demo"
        )
    fit_tok = seqs[: args.fit_seqs]
    cal_tok = seqs[args.fit_seqs : 2 * args.fit_seqs]
    demo_clean = seqs[2 * args.fit_seqs : 2 * args.fit_seqs + args.n_demo]
    print(f"[heal] disjoint splits: fit={fit_tok.shape[0]} cal={cal_tok.shape[0]} "
          f"demo={demo_clean.shape[0]}  n_seeds={args.n_seeds}")

    # ---- 1. localizer ----
    print("=== train per-token energy head ===")
    score, d = train_localizer(
        model, fit_tok, t_eval, device, train_rate=args.train_rate,
        margin=args.margin, steps=args.head_steps, lr=args.lr, seed=args.seed,
    )

    # ---- 2. thresholds + GT-FREE operating-point selection (max cal-set F1) ----
    cal_corr = corrupt_token_ids(
        cal_tok.clone(), vocab_size=K, corrupt_rate=args.corrupt_rate, seed=args.seed + 1
    )
    fprs = [float(x) for x in args.target_fprs.split(",") if x.strip()]
    thr_by_fpr = {}
    for fpr in fprs:
        thr, cal_stats = calibrate_threshold(score, cal_tok, cal_corr, target_fpr=fpr)
        thr_by_fpr[fpr] = (thr, cal_stats)
    sel_fpr = max(fprs, key=lambda f: thr_by_fpr[f][1]["f1"])  # GT-free (cal set only)

    # ---- 3. demo: corrupt over n_seeds, localize (energy only), inpaint, score ----
    print(f"=== heal sweep (mean over {args.n_seeds} corruption seeds) ===")
    print(f"{'fpr':>5} {'thr':>7} {'loc_P':>6} {'loc_R':>6} {'fix':>6} {'dmg':>6} "
          f"{'net/corrupt':>14} {'delta_ws':>10}")
    demo_corrs = [
        corrupt_token_ids(demo_clean.clone(), vocab_size=K,
                          corrupt_rate=args.corrupt_rate, seed=args.seed + 100 + s)
        for s in range(args.n_seeds)
    ]
    E_demos = [score(dc) for dc in demo_corrs]  # per-token energy; GT never used here

    sweep = []
    example = None
    for fpr in fprs:
        thr, cal_stats = thr_by_fpr[fpr]
        per_seed = []
        first_artifacts = None
        for s in range(args.n_seeds):
            dc = demo_corrs[s]
            mask = E_demos[s] > thr
            healed = inpaint(model, dc, mask, nfe=args.nfe, device=device)
            m = score_healing(demo_clean, dc, healed, mask, dc != demo_clean)
            per_seed.append(m)
            if s == 0:
                first_artifacts = (dc, mask, healed)
        agg = aggregate(per_seed)
        tag = "  <- selected" if fpr == sel_fpr else ""
        print(f"{fpr:>5.2f} {thr:>7.3f} {agg['loc_precision']:>6.3f} "
              f"{agg['loc_recall']:>6.3f} {agg['fix_rate']:>6.3f} {agg['damage_rate']:>6.3f} "
              f"{agg['net_per_corrupt']:>+8.3f}±{agg['net_per_corrupt_std']:.3f} "
              f"{agg['delta_wholeseq']:>+10.4f}{tag}")
        sweep.append({"target_fpr": fpr, "threshold": thr, "calibration": cal_stats, **agg})
        if fpr == sel_fpr:
            example = first_artifacts

    # ---- 4. example dump from the SELECTED (cal-F1) operating point, seed 0 ----
    dc0, mask0, healed0 = example
    clean = demo_clean.cpu()
    print(f"\n--- example[0] @ selected fpr={sel_fpr} (chosen by cal-set F1) ---")
    print(f"  clean : {_decode(clean[0])!r}")
    print(f"  corr  : {_decode(dc0.cpu()[0])!r}")
    print(f"  truec : {''.join('^' if x else ' ' for x in (dc0.cpu()[0] != clean[0]).tolist())}")
    print(f"  flag  : {''.join('*' if x else ' ' for x in mask0.cpu()[0].tolist())}")
    print(f"  healed: {_decode(healed0.cpu()[0])!r}")

    sel = next(r for r in sweep if r["target_fpr"] == sel_fpr)
    print(f"\n=== HEADLINE @ selected fpr={sel_fpr} (mean±std over {args.n_seeds} seeds) ===")
    print(f"  fix_rate    = {sel['fix_rate']:.3f}   (corrupt token -> correct)")
    print(f"  damage_rate = {sel['damage_rate']:.3f}   (clean token -> broken)")
    print(f"  net/corrupt = {sel['net_per_corrupt']:+.3f} ± {sel['net_per_corrupt_std']:.3f}"
          f"   (net tokens recovered per corrupt token; >0 ⇒ net benefit)")
    print(f"  delta_ws    = {sel['delta_wholeseq']:+.4f} ± {sel['delta_wholeseq_std']:.4f}"
          f"   (whole-seq; diluted, capped near corrupt_rate — diagnostic only)")

    rows = {
        "ckpt": args.ckpt, "K": K, "L": L, "t_max": float(model.dfm.t_max),
        "t_eval": t_eval, "d_model": d, "nfe": args.nfe, "n_seeds": args.n_seeds,
        "corrupt_rate": args.corrupt_rate, "train_rate": args.train_rate,
        "n_demo": int(demo_clean.shape[0]),
        "selected_fpr": sel_fpr, "selection": "max cal-set F1 (GT-free on demo)",
        "sweep": sweep,
        "examples": [
            {
                "clean": _decode(clean[b]), "corrupted": _decode(dc0.cpu()[b]),
                "healed": _decode(healed0.cpu()[b]),
                "true_corrupt": [bool(x) for x in (dc0.cpu()[b] != clean[b]).tolist()],
                "flagged": [bool(x) for x in mask0.cpu()[b].tolist()],
            }
            for b in range(min(4, demo_clean.shape[0]))
        ],
    }
    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(json.dumps(rows, indent=2))
    print(f"\nWrote {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
